on:
  push:
    branches:
      - main

name: Deploy to Amazon Lambda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          pip install -r requirements.txt -t .
          pip install pillow --platform manylinux1_x86_64 --only-binary=:all: -t ./python
      - name: Build and deploy lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          zip -x .git -r lambda.zip ./*
          mv lambda.zip /tmp/lambda.zip
          aws lambda update-function-code --region ap-northeast-1 --function-name CoCNonKP --zip-file fileb:///tmp/lambda.zip --publish
      - name: Notify result to slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*Deploy Lambda*"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
